name: Gridlab
favicon: null
layout_spectrum: 0.1921
typography_spectrum: 0.33515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151b20'
    - '#e24929'
    - '#666a6f'
    - '#f3f2f2'
    - '#b5b7b9'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
