name: Gridlab
favicon: null
layout_spectrum: 0
typography_spectrum: 0.59234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f2f1'
    - '#012437'
    - '#4d6471'
    - '#d8cebf'
    - '#998259'
  brandStrength: 0
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 1
purpose: []
