name: Gridlab
favicon: null
layout_spectrum: 0.1921
typography_spectrum: 0.33515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1d1b'
    - '#e24929'
    - '#47a9f4'
    - '#b9b8b7'
    - '#fefefe'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
