name: Gridlab
favicon: null
layout_spectrum: 0.1921
typography_spectrum: 0.33515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0e11'
    - '#3d394f'
    - '#ffffff'
    - '#e96c78'
    - '#be2402'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
