name: Gridlab
favicon: null
layout_spectrum: 0.1921
typography_spectrum: 0.33515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bd0000'
    - '#ffffff'
    - '#181c18'
    - '#00b2ff'
    - '#eca5a6'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
