name: Gridlab
favicon: null
layout_spectrum: 0.36603
typography_spectrum: 0.33515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c43235'
    - '#300032'
    - '#e6e6e8'
    - '#d67274'
    - '#efc9a0'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
