name: Gridlab
favicon: null
layout_spectrum: 0.36603
typography_spectrum: 0.33515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4c6b6e'
    - '#72a4a3'
    - '#99ddd9'
    - '#1f272e'
    - '#3d4d4c'
  brandStrength: 0
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
