name: Gridlab
favicon: null
layout_spectrum: 0.44507
typography_spectrum: 0.40742909675464034
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1d1b'
    - '#e24929'
    - '#47a9f4'
    - '#b9b8b7'
    - '#fefefe'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.9628564689774066
purpose: []
