name: Gridlab
favicon: null
layout_spectrum: 0.36603
typography_spectrum: 0.33515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#182f57'
    - '#b2b5ba'
    - '#ffffff'
    - '#6b788d'
    - '#8196a2'
  brandStrength: 0
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
