name: Gridlab
favicon: null
layout_spectrum: 0.36603
typography_spectrum: 0.33515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f272e'
    - '#99ddd9'
    - '#4c6b6e'
    - '#72a4a3'
    - '#000000'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
