name: Gridlab
favicon: null
layout_spectrum: 0.62247
typography_spectrum: 0.33515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e62739'
    - '#e1e8f0'
    - '#6ed3cf'
    - '#9068be'
    - '#e46f7d'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 1
  rhythmicContrast: 1
purpose: []
