name: Gridlab
favicon: null
layout_spectrum: 0.1077
typography_spectrum: 0.59234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#291224'
    - '#f04349'
    - '#732331'
    - '#cec19a'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
