name: Gridlab
favicon: null
layout_spectrum: 0.09127
typography_spectrum: 0.33515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f2f1'
    - '#c03e23'
    - '#50adf4'
    - '#1d1d1b'
    - '#575755'
  brandStrength: 0
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 1
purpose: []
