name: Gridlab
favicon: null
layout_spectrum: 0.63512
typography_spectrum: 0.33515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f0f1'
    - '#0177e5'
    - '#ff1b42'
    - '#9da8b6'
    - '#0d3255'
  brandStrength: 1
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 1
purpose: []
