name: Gridlab
favicon: null
layout_spectrum: 0.1921
typography_spectrum: 0.33515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#faf9f8'
    - '#47a9f4'
    - '#9dcef2'
    - '#7b7b79'
    - '#40403e'
  brandStrength: 1
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
